### ISSUE TITLE
Migrate to use kube_codegen.sh

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#305]
```
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
```
When trying to upgrade k8 dependencies, I see the following warnings.  

Kueue has https://github.com/kubernetes-sigs/kueue/issues/1134 tracking this so it would be ideal to have a similar way of generating these dependencies.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/kueue/pull/1151 looks to be a good example to follow.
/help

**Comment by liangyuanpeng** [comment]
I want to try it. 
/assign

**Comment by ashnehete** [comment]
If there is no progress on this issue, can I pick it up?

**Comment by ahg-g** [comment]
yes please!

**Comment by ashnehete** [comment]
The problem seems to be that the new tool enforces a directory structure equal to the package name i.e. `sig.k8s.io/jobset/api` according to [docs](https://github.com/kubernetes/code-generator/blob/791c213a776b4b92f9af0805c1cf57c118ba951c/kube_codegen.sh#L39-L48). Is this a problem for us? Becuase this is something which has halted this same issue over at [Kueue](https://github.com/kubernetes-sigs/kueue/pull/1151/files#r1336826593).

**Comment by mimowo** [comment]
@ashnehete You may consider the similar approach as we do here: https://github.com/kubernetes-sigs/kueue/pull/1151

**Comment by kannon92** [comment]
Our hope is to follow a similar idea for Kueue.  If you are still interested in working on this, please follow https://github.com/kubernetes-sigs/kueue/pull/1151.

I run into this issue in my workflow also because I don't follow the recommended clone structure for code-generator.
