### ISSUE TITLE
☂️ Requirements for v0.4.0 release

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#350]
Targeting release around March 1st, 2024.

**Must haves**
- [x] https://github.com/kubernetes-sigs/jobset/issues/344
- [x] #392 
- [x] https://github.com/kubernetes-sigs/jobset/issues/104

**Nice to haves**
- [ ] https://github.com/kubernetes-sigs/jobset/issues/279
- [ ] https://github.com/kubernetes-sigs/jobset/issues/75
- [ ] https://github.com/kubernetes-sigs/jobset/issues/262
- [ ] https://github.com/kubernetes-sigs/jobset/issues/380

**Comment by ahg-g** [comment]
lets startup policy as well as nice to have

**Comment by danielvegamyhre** [comment]
> lets startup policy as well as nice to have

Sounds good, added.

**Comment by dejanzele** [comment]
Which date is targetted for v0.4.0 release @danielvegamyhre ?

**Comment by danielvegamyhre** [comment]
Around March 1st.

**Comment by danielvegamyhre** [comment]
Added #75 to "nice to haves," since it is important but we are unlikely to have time to complete it by the next release.

**Comment by danielvegamyhre** [comment]
Added Graduating API to Beta to must-haves. https://github.com/kubernetes-sigs/jobset/issues/380

**Comment by ahg-g** [comment]
I would move https://github.com/kubernetes-sigs/jobset/issues/262 to the next release, and just focus on startup policy and v1 graduation in the 0.4 release.

The reason is that I would like to make sure we have a conclusion on https://github.com/kubernetes/enhancements/pull/4479 before we commit on the failure policy api, and I don't want to block the 0.4 release on that.

I think https://github.com/kubernetes-sigs/jobset/issues/344, https://github.com/kubernetes-sigs/jobset/issues/104 and https://github.com/kubernetes-sigs/jobset/issues/380 merits a release.

**Comment by ahg-g** [comment]
This also leaves 0.5 with two sizable enhancements: failure policy and TTL with the exclusive placement API enhancement as a nice to have.

**Comment by danielvegamyhre** [comment]
> I would move #262 to the next release, and just focus on startup policy and v1 graduation in the 0.4 release.
> 
> The reason is that I would like to make sure we have a conclusion on [kubernetes/enhancements#4479](https://github.com/kubernetes/enhancements/pull/4479) before we commit on the failure policy api, and I don't want to block the 0.4 release on that.
> 
> I think #344, #104 and #380 merits a release.

Makes sense. In addition, #392 was an important change for fast restarts / failure recovery, which I think is important to included in a release ASAP. I will update the release requirements accordingly.

**Comment by ahg-g** [comment]
True! lets add that to the list above and in the release notes.

**Comment by danielvegamyhre** [comment]
v0.4.0 has been released 🥳
