### ISSUE TITLE
Allow to mutate PodTemplate when suspending a JobSet and support resuming such JobSet

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/jobset#624]
There are currently two related issues which prevent JobSet - Kueue integration:
1. JobSet rejects mutation of PodTemplate on suspend

When Kueue evicts a workload (represented by JobSet) it stops the JobSet and tries to restore the PodTemplate to enable re-admitting the same JobSet to another ResourceFlavor (with potentially different nodeSelectors).
For example, the following e2e test for Job shows how Kueue can preempt a workload and re-admit with another nodeSelector: [link](https://github.com/kubernetes-sigs/kueue/blob/4b90a76a424be5456165f40a304dbe557ab4d422/test/e2e/singlecluster/e2e_test.go#L253-L287).

However, the integration with Kueue does not work currently, because the Kueue request to suspend
the JobSet fails if it also wants to update the PodTemaplte.

**Comment by danielvegamyhre** [comment]
Let's fix this, but rather than solely doing a one-off fix here, we need to iron out the specific requirements for JobSet + Kueue integration, as well as align our roadmaps so changes in Kueue don't break JobSet integration.

We just recently had an issue similar to this, with Kueue trying to mutate certain podTemplate fields on suspended JobSets, but these are immutable fields in JobSet, which led to a customer/user reporting the issue. (https://github.com/kubernetes-sigs/jobset/issues/579)

cc @alculquicondor @mimowo @ahg-g @kannon92

**Comment by mimowo** [comment]
I think this is a good point. I think on the technical layer, we should keep extending the JobSet e2e test suite which was started by recently.

**Comment by mimowo** [comment]
The proposal for the e2e test scenario which covers this and https://github.com/kubernetes-sigs/jobset/pull/623: https://github.com/kubernetes-sigs/jobset/pull/623#discussion_r1691860656
